apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: devops-services
spec:
  nodeSelector:
    nature: ci
  tolerations:
    - effect: NoSchedule
      key: nature
      operator: Equal
      value: ci
  containers:
    - name: go
      image: sam0392in/jenkins-agents:go-agent-0.2
      command:
        - cat
      tty: true
    - name: imagebuilder
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /bin/sh
      args:
        - -c
        - /busybox/cat
      tty: true
      env:
        - name: AWS_SDK_LOAD_CONFIG
          value: 'true'
    - name: cicd
      command:
        - cat
      image: 123445566778.dkr.ecr.eu-west-1.amazonaws.com/sam/cicd:4.9.0
      tty: true
      volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkinsvolume
        - mountPath: /var/lib/docker
          name: dockervolume
        - mountPath: /pullSecret
          name: docker-secret
  imagePullSecrets:
    - name: dockerhubpro
  serviceAccountName: jenkins
  volumes:
    - emptyDir: {}
      name: jenkinsvolume
    - emptyDir: {}
      name: dockervolume
    - name: docker-secret
      secret:
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: dockerhubpro