apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: tcp
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
#   loadBalancerClass: {{ .Values.service.loadBalancerClass }}